### ISSUE TITLE
Citing use of odeintw

### ISSUE THREAD

**Issue by iamholger** [WarrenWeckesser/odeintw#1]
Hi Warren, we are using odeintw in an upcoming publication. Is there a reference we can cite to acknowledge your work?
Thanks,
Holger

**Comment by WarrenWeckesser** [comment]
Hi Holger,

There is no journal publication about odeintw, so currently the only concrete thing to reference is the github site, `https://github.com/WarrenWeckesser/odeintw`.  There are several suggestions among the answers in this discussion on academia.stackexchange.com: https://academia.stackexchange.com/questions/14010/how-do-you-cite-a-github-repository

One of those answers links to https://guides.github.com/activities/citable-code/, which explains how to use Zenodo to get a DOI for a github repository.  That looks interesting, but until I learn more about it, I'm hesitant about signing up with Zenodo and giving them the repository access they need.

**Comment by WarrenWeckesser** [comment]
P.S. Thanks for thinking of acknowledging the project!

**Comment by iamholger** [comment]
Thanks a lot, we'll go ahead citing the github page then. Thanks, Holger
