### ISSUE TITLE
Can/could odeintw work with pip?

### ISSUE THREAD

**Issue by joelmiller** [WarrenWeckesser/odeintw#2]
I'm writing a package which would rely on odeintw for a few steps.  I would like to make my package installable through [pip](https://pip.pypa.io/en/stable/).  However, I don't think I'll be able to get it to automatically install odeintw, because it doesn't seem to be available through pip.  So that makes the installation a lot more involved.  Have I missed something?  Or, would it be possible to do arrange for pip to install odeintw?

thanks!

**Comment by joelmiller** [comment]
Never mind - figured out the proper syntax for the requirements.txt file to do this...

**Comment by WarrenWeckesser** [comment]
OK, but I'll still look into this.  It isn't that hard to add something to PyPI, and just one person asking is sufficient motivation to do it for this project.

**Comment by fretchen** [comment]
It would be super helpful for simple integration.

**Comment by WarrenWeckesser** [comment]
@fretchen, I agree.  I'm reopening this so it stays on my to-do list.

**Comment by WarrenWeckesser** [comment]
I uploaded odeintw to PyPI: https://pypi.org/project/odeintw/

I'm closing the issue, but comment here if you run into any problems using the package on PyPI.
