### ISSUE TITLE
Odeintw Runtime problems

### ISSUE THREAD

**Issue by SamsTheGreatest** [WarrenWeckesser/odeintw#3]
I'm was asked to solve a system of complex odes in python, so I found this amazing wrapper for odeint. 
I created a huge 1D array of initial values and passed it to the Odeintw function. It works absolutely fine with problem's initial values and 3481 odes. However, when I increase the number of odes to 3600(I have a square matrix with them, so the transition is represented by 59 to 60) the runtime suddenly rockets from **5 to 400 seconds**. Keeping 3600 odes I changed the array of initial values right before the function with _y0=np.zeros_like(y0)_. The execution time changed again to **0.5 seconds**. While having _y0=0_ I changed the number of ODEs to 1 Billion and the function solved them in **6 seconds**. I also tried setting initial conditions to very small values via _y0=np.ones_like(y0)/10000000000000000_ and the time was again pretty small. Changing the number of odes again to 4096 resulted in runtime **9 seconds**.
**What could be the problem and how can I avoid it?** I really need to go up to 100 Million ODEs with the current initial conditions(the values in the array vary from 10^(-81) to 0.1)

**Comment by WarrenWeckesser** [comment]
What does the solution look like when the initial conditions are all zero?  Does the behavior of the solution change much when you change the number of ODEs from 3481 to 3600?

As you know, `odeintw` is a wrapper of `scipy.integrate.odeint`, and `odeint` is a wrapper of the Fortran code LSODA.  LSODA (like all good ODE solvers) is adaptive.  When the solution is not changing much, the solver can use large step sizes.  Try plotting a few components of the solution when you change the initial conditions.  You might find that for some values, the solution remains nearly constant, or quickly settles into a steady state, and the solver can then take very large steps.  For other initial conditions, you might have oscillations or chaotic behavior, where the solver's step sizes are limited by the variability of the solution.

**Comment by SamsTheGreatest** [comment]
Dear Warren,
When setting initial conditions to 0, the solution of all ODEs is a 0 straight line for any number of ODEs.
A change from 59 to 60(3481 to 3600) with required initial conditions:
1) Taking any element of the ODE matrix which is far from the “changing edge”: Solution doesn’t change, the solution smoothly oscillates.
2)Element 3480(close to the edge): Solution changes. See the screenshots below. On the top is the  shape of the output(50 time steps, number of ODEs), execution time is right below it, followed by a plot.

So, as I understand, you are intending to say that for a more chaotic case the number of steps taken by the solver increases, making the code run longer?

In my case I have an infinite coupled ODEs arranged in a matrix. The elements of the matrix are behaving exactly as predicted in both cases(3481 and 3600). Logically, expending the ODE matrix should not make a difference on the overall dynamics of the matrix, since the the amplitudes of the solutions near the “edge” of the matrix is already infinitesimally small. So, as for me, changing 3481 to 3600 should not make such a big difference. For example, if I solve this matrix for 3721, the execution time is, again, around 0.5 sec. Furthermore, if I go up to 3844, the time rockets to 100 sec again.

Is there a way to neglect these variations of a small amplitude? As I understand, this might fix these abnormal time fluctuations?

**Comment by SamsTheGreatest** [comment]
Dear Warren,
When setting initial conditions to 0, the solution of all ODEs is a 0 straight line for any number of ODEs.
A change from 59 to 60(3481 to 3600) with the required initial conditions:

1. Taking any element of the ODE matrix which is far from the “changing edge”: Solution doesn’t change, the solution smoothly oscillates.
2. Element 3480(close to the edge): Solution changes. See the screenshots for the same element of the matrix. I presented the shape of the output(50 time steps, number of ODEs), execution time right below it, followed by a plot.

So, as I understand, you are intending to say that for a more chaotic case the number of steps taken by the solver increases, making the code run longer?

In my case, I have an infinite coupled ODEs arranged in a matrix. The elements of the matrix are behaving exactly as predicted in both cases(3481 and 3600). Logically, expending the ODE matrix should not make a difference on the overall dynamics of the matrix, since the amplitudes of the solutions near the “edge” of the matrix are already infinitesimally small. So, as for me, changing 3481 to 3600 should not make such a big difference. For example, if I solve this matrix for 3721, the execution time is, again, around 0.5 sec. Furthermore, if I go up to 3844, the time rockets to 100 sec again.

Is there a way to neglect these variations of a small amplitude? As I understand, this might fix these abnormal time fluctuations?
<img width="393" alt="screen shot 2018-07-24 at 23 43 47" src="https://user-images.githubusercontent.com/41646769/43171159-d2d502fe-8fa0-11e8-9aee-0a2f8c3a8b0d.png">
<img width="388" alt="screen shot 2018-07-24 at 23 43 54" src="https://user-images.githubusercontent.com/41646769/43171169-d7d3b250-8fa0-11e8-87a9-63f2bcb6ce12.png">

**Comment by WarrenWeckesser** [comment]
> So, as I understand, you are intending to say that for a more chaotic case the number of steps taken by the solver increases, making the code run longer?

Yes--but that would be true for any adaptive solver.  All it means is that the change in speed that occurs when you make the initial conditions all zero is probably because the solution is identically zero and the solver takes very big steps.  The change in speed as you vary the size of the system might be because of something else.

Try adding the argument `full_output=True`, and take a look at second value, `infodict`, that is returned.  See the [`odeint` docstring](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html) for a description of the argument and the information returned in `infodict`.  In particular, it might be interesting to see the value of `infodict['hu'].min()` and `infodict['nst']` for the solutions that are fast and for the solutions that are slow.

**Comment by SamsTheGreatest** [comment]
Dear Warren, 
I get your point. Here is the required output of infodict with an included sum of `infodict['nst'].sum()`:

1. 59*59(3481): 
- `infodict['hu'].min()`=0.000230278407993
- `infodict['nst']`=[  12   16   20   43   85  130  173  217  262  307  348  392  436  480  519
  562  603  642  685  727  769  813  854  895  935  975 1023 1070 1109 1150
 1189 1228 1272 1320 1365 1404 1445 1490 1531 1580 1628 1675 1719 1769 1818
 1866 1915 1962 2009]
- `infodict['nst'].sum()`=46437
- Time=0.783398866653 sec

2. 60*60(3600): 
- `infodict['hu'].min()`=0.000319026052474
- `infodict['nst']`=[  12   16   20   44   88  131  172  215  260  303  345  386  430  470  493
  503  512  521  528  533  538  543  548  554  558  563  568  573  580  590
  605  639  692  751  810  868  925  983 1037 1090 1150 1207 1263 1319 1376
 1432 1488 1545 1601]
- `infodict['nst'].sum()`=32378
- Time=400 sec
3. 61*61(3721): 
- `infodict['hu'].min()`=0.000226739233335
- `infodict['nst']`=[  12   16   20   44   87  130  174  219  265  309  352  393  437  483  525
  567  614  656  699  744  786  830  872  916  956 1005 1051 1097 1148 1192
 1236 1282 1330 1375 1428 1476 1519 1571 1616 1657 1723 1775 1825 1874 1917
 1977 2023 2067 2122]
- `infodict['nst'].sum()`=48392
- Time=0.735090970993 sec

As I understand from the output, the time step increase and the total number of steps decrease for the 60*60 case.

Could be also worth mentioning that the input function is represented as a sparse matrix, in case it would make any difference...

**Comment by WarrenWeckesser** [comment]
@SamsTheGreatest, I'm closing this issue.  At the time, I didn't see anything that I could do to odeintw to address the issue.  I assume that by now you have worked around the issue.  Sorry I couldn't be of more help!
