### ISSUE TITLE
Support with complex matrices

### ISSUE THREAD

**Issue by albertomercurio** [WarrenWeckesser/odeintw#6]
Hello,
when i insert a complex matrix it returns
```
TypeError: Cannot cast array data from dtype('complex128') to dtype('float64') according to the rule 'safe'
```
is it possible to support complex matrices also?

**Comment by WarrenWeckesser** [comment]
`odeintw` supports complex matrices.  Can you create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that generates that error?

Also, which versions of scipy and numpy are you using?

**Comment by WarrenWeckesser** [comment]
I can create that error if the function that defines the differential equations returns a complex array, but the initial condition `y0` is real.  If your system is complex, the data type of `y0` must be complex.  You might be able to fix your problem by passing `y0.astype(np.complex128)` to `odeintw` (where `y0` is the array of initial conditions).

**Comment by albertomercurio** [comment]
Perfect, it works now!

**Comment by WarrenWeckesser** [comment]
Great, thanks for letting me know.
